PROMPT=""
PROMPT+=' %{$fg_bold[cyan]%}%c%{$reset_color%}'
PROMPT+=' ${KUBE_PS1_CONTEXT}'
PROMPT+=' $(git_prompt_info)'
PROMPT+='%{$fg_bold[white]%}%D{%Y/%m/%d} %* %{$reset_color%}'
PROMPT+="%(?:%{$fg_bold[green]%}$:%{$fg_bold[red]%}$)%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
